History
sircoderin/core-component pull request #20
Opened 2023-03-07 20:44 UTC by andrewtookay

2023-03-08 14:43 UTC, sircoderin requested changes

2023-03-08 14:43 UTC, sircoderin commented on app/dot/cpp/core/services/HistoryService.java
> +  private List<HistoryEntry> getHistoryEntries(EntityService<?, ?> entityService, BaseEntity entity)
Maybe rename entity cu currentState?

2023-03-08 17:04 UTC, andrewtookay commented on app/dot/cpp/core/exceptions/FormException.java
> +  private final transient List<ValidationError> formErrors;
because List<ValidationError> is not serializable and it was a critical code smell

2023-03-08 17:07 UTC, andrewtookay commented on app/dot/cpp/core/models/HistoryEntry.java
> +  }
It was not needed as this class is never used in a different manner, you use the constructor, set everything at creation and then you read those final variables. Its fields do not need to be set individually at any point. It is simple and clean this way.

2023-03-08 17:07 UTC, andrewtookay commented on app/dot/cpp/core/services/EntityService.java
> +  // use findByIdOrGetNewEntity where needed and replace this behaviour
Yes! It's coming up in the next episode, the refactor PR.

2023-03-08 17:14 UTC, andrewtookay commented on app/dot/cpp/core/services/HistoryService.java
> +  public List<HistoryEntry> getHistoryEntriesById(EntityService<?, ?> entityService, String id)
These <?, ?> are always extensions of BaseEntity and BaseRequest so this class can be parameterized. I can show you what I came up.

2023-03-08 17:19 UTC, andrewtookay commented on app/dot/cpp/core/services/HistoryService.java
> +  private List<HistoryEntry> getHistoryEntries(EntityService<?, ?> entityService, BaseEntity entity)
or currentEntity I guess?

2023-03-08 17:22 UTC, andrewtookay commented on app/dot/cpp/core/services/RequestErrorService.java
> +   */
I think I had the default checkstyle at the time and it was asking for this or something.

2023-03-08 17:24 UTC, andrewtookay commented on app/dot/cpp/core/services/HistoryService.java
> +        historyEntities.stream().map(BaseEntity::getModifiedBy).collect(Collectors.toSet());
I renamed this to modifiedByUserIdSet.

2023-03-08 17:29 UTC, andrewtookay commented on app/dot/cpp/core/services/HistoryService.java
> +    final var historyEntities = entityService.listHistory(entity.getTrackingId());
I'm not really sure about this, to me it seemed quite explicit, like those are the entities found in the history collection. I could call them oldEntities but it seems a little silly. I think it's the historyEntries and historyEntities that can cause a little confusion, but it's not like the method is that complex and hard to follow.

2023-03-09 16:41 UTC, sircoderin commented on app/dot/cpp/core/services/EntityService.java
> +                FilterBuilder.newInstance()
might as welll use Filters.eq here

2023-03-09 16:42 UTC, sircoderin commented on app/dot/cpp/core/services/EntityService.java
> +                        new ArrayList<>(modifiedByUserIdSet)
can't we loop the set without casting?

2023-03-09 16:43 UTC, sircoderin commented on app/dot/cpp/core/services/EntityService.java
> +        historyStates.stream().map(BaseEntity::getModifiedBy).collect(Collectors.toSet());
we can use distinct instead of toSet in order to make this a list from te start

2023-03-09 16:46 UTC, sircoderin commented on app/dot/cpp/core/services/EntityService.java
> +                    .orEq(
shouldn't this be using "in"?

2023-03-09 16:49 UTC, sircoderin commented on app/dot/cpp/core/services/EntityService.java
> +                    .build())
Might as well inline this filter

2023-03-09 17:44 UTC, merged